export const LOGIN = {
  FAILURE: 'USER/AUTHORIZATION_FAILURE',
  START: 'USER/LOGIN_START',
  SUCCESS: 'USER/LOGIN_SUCCESS',
};
export const AUTHORIZATION_FORM = {
  OPEN: 'AUTHORIZATION_FORM/OPEN',
  CLOSE: 'AUTHORIZATION_FORM/CLOSE',
};
export const REGISTRATION_FORM = {
  OPEN: 'REGISTRATION_FORM/OPEN',
  CLOSE: 'REGISTRATION_FORM/CLOSE',
};
