export const LOGIN = {
  FAILURE: 'USER/LOGIN_FAILURE',
  START: 'USER/LOGIN_START',
  SUCCESS: 'USER/LOGIN_SUCCESS',
  CLEAR_LOGIN_ERRS: 'USER/CLEAR_LOGIN_ERRS',
  LOGOUT: 'USER/LOGOUT',
  LOGIN_VIA_LOCALSTORAGE: 'USER/LOGIN_VIA_LOCALSTORAGE',
};
export const AUTHORIZATION_FORM = {
  OPEN: 'AUTHORIZATION_FORM/OPEN',
  CLOSE: 'AUTHORIZATION_FORM/CLOSE',
};
export const REGISTRATION_FORM = {
  OPEN: 'REGISTRATION_FORM/OPEN',
  CLOSE: 'REGISTRATION_FORM/CLOSE',
};
