export const LOG_IN_FORM = {
  CLOSE: 'LOG_IN_FORM/CLOSE',
  OPEN: 'LOG_IN_FORM/OPEN',
};
export const LOG_IN = {
  FAILURE: 'USER/LOG_IN_FAILURE',
  WITH_LOCALSTORAGE: 'USER/LOG_IN_WITH_LOCALSTORAGE',
  START: 'USER/LOG_IN_START',
  SUCCESS: 'USER/LOG_IN_SUCCESS',
};
export const LOG_OUT = 'USER/LOG_OUT';
export const REGISTRATION_FORM = {
  OPEN: 'REGISTRATION_FORM/OPEN',
  CLOSE: 'REGISTRATION_FORM/CLOSE',
};

