export const FETCH_FAILURE = `COUNTRY/FETCH_FAILURE`;
export const FETCH_SUCCESS = `COUNTRY/FETCH_SUCCESS`;
export const SELECT_COUNTRY = `COUNTRY/SELECT_COUNTRY`;
export const START_REQUEST = `COUNTRY/FETCH_REQUEST`;
