export const FETCH = {
  START: 'COUNTRY/FETCH_START',
  FAILURE: 'COUNTRY/FETCH_FAILURE',
};
export const FETCH_COUNTRIES_SUCCESS = 'COUNTRY/FETCH_COUNTRIES_SUCCESS';
export const FETCH_COUNTRY_SUCCESS = 'COUNTRY/FETCH_COUNTRY_SUCCESS';
